version: '3.1'
services:
  postgresql:
    image: postgres:11.6-alpine
    container_name: simple-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"