spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple-postgres
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    mapping-resources: "Jsonb.hbm.xml"
axon:
  axon server:
    enabled: false
  serializer:
    general: jackson